### ISSUE TITLE
How can I serialise with no indentation formating?

### ISSUE THREAD

**Issue by 7sharp9** [Microsoft/fsharplu#6]
How can I serialise with no indentation formating?

**Comment by blumu** [comment]
You would need to augment the `With` functor defined in (FSharpLu.Json/WithFunctor.fs)
and add a new member to pass `Formatting.None` instead of `Formatting.Indented` to JsonConvert.SerializeObject. (See [Netwonsoft doc](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Formatting.htm))
```
type With< ^S when ^S : (static member settings : JsonSerializerSettings) > =
    /// Serialize an object to Json with the specified converter
    static member inline public serializeNoIndent (obj:^T) =
        let settings = (^S:(static member settings : JsonSerializerSettings)())
        JsonConvert.SerializeObject(obj, Formatting.None, settings)
```
Alternatively you could add the formatting option as a static parameter to the `With` functor (like it's done for `settings`).

**Comment by blumu** [comment]
Fixed in master: the `Formatting` JSon.Net parameter can be specified to the 'With' Functor:
This can be used as follows to define a serializer with no indentation:
```
type Settings =
    static member settings =
        let s = JsonSerializerSettings(
                    NullValueHandling = NullValueHandling.Ignore,
                    MissingMemberHandling = MissingMemberHandling.Error)
        s.Converters.Add(CompactUnionJsonConverter())
        s

    static member formatting = Formatting.None

type MySerializer = With<Internal.Settings>

MySerializer.serialize [ "bla" ]
```
